#!/usr/bin/env python3
"""
Genera una piccola tabella simbolica C ordinata per indirizzo partendo da `nm -n`.

Manteniamo solo simboli di testo per evitare drift degli indirizzi dati fra
pass1 e link finale. Questo e' sufficiente per stack trace e crash reporter.
"""

from __future__ import annotations

import re
import os
import subprocess
import sys
from pathlib import Path


KEEP_TYPES = {"T", "t", "W", "w"}
SKIP_PREFIXES = (".L", "$", "__gnu_", "__abi_")


def should_keep(name: str, typ: str) -> bool:
    if typ not in KEEP_TYPES:
        return False
    if not name:
        return False
    if name.startswith(SKIP_PREFIXES):
        return False
    return True


def main() -> int:
    if len(sys.argv) != 3:
        print("usage: gen_ksyms.py <elf> <out.c>", file=sys.stderr)
        return 1

    elf = Path(sys.argv[1])
    out = Path(sys.argv[2])

    nm_bin = os.environ.get("NM", "nm")
    nm_out = subprocess.check_output([nm_bin, "-n", str(elf)], text=True)
    entries: list[tuple[int, str]] = []

    for line in nm_out.splitlines():
        m = re.match(r"^([0-9A-Fa-f]+)\s+([A-Za-z])\s+(.+)$", line.strip())
        if not m:
            continue
        addr = int(m.group(1), 16)
        typ = m.group(2)
        name = m.group(3).strip()
        if should_keep(name, typ):
            entries.append((addr, name))

    with out.open("w", encoding="ascii") as fh:
        fh.write("/* Auto-generated by tools/gen_ksyms.py. */\n")
        fh.write('#include "kdebug.h"\n\n')
        fh.write("const ksym_entry_t kdebug_ksymtab[] = {\n")
        for addr, name in entries:
            safe = name.replace("\\", "\\\\").replace('"', '\\"')
            fh.write(f'    {{ 0x{addr:016X}ULL, "{safe}" }},\n')
        if not entries:
            fh.write("    { 0ULL, 0 },\n")
        fh.write("};\n\n")
        fh.write(f"const uint32_t kdebug_ksymtab_count = {len(entries)}U;\n")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
